import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  pesquisa: {
    marginTop: 21,
    width: "100%",
    height: 110,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: " #FFF3E8",
    marginBottom: 0,
    paddingBottom: 0,
    gap: 0,
  },
  innerShadow: {
    width: 374,
    height: 58,
    borderRadius: 40,
    backgroundColor: "rgba(253, 211, 192, 0.71)",
    overflow: "hidden",
    position: "relative",
  },
  pesquisaInput: {
    width: "100%",
    height: "100%",
    borderRadius: 40,
    paddingHorizontal: 20,
    backgroundColor: "transparent",
    zIndex: 2,
  },
  gradientOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 40,
    zIndex: 1,
  },
  filtros: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: "100%",
    paddingHorizontal: 20,
  },
  imagem: {
    justifyContent: "center",
    alignContent: "center",
    alignSelf: "center",
  },
  objfiltro: {
    marginTop: 10,
    flexDirection: "row",
    gap: 7,
    backgroundColor: "rgba(251, 198, 171, 0.41)",
    borderRadius: 40,
    padding: 5,
    paddingHorizontal: 24,
    marginRight: 10,
  },
  objfiltroapli: {
    marginTop: 10,
    flexDirection: "row",
    gap: 7,
    backgroundColor: "rgba(251, 198, 171, 0.41)",
    borderRadius: 40,
    padding: 5,
    paddingHorizontal: 14,
    marginRight: 10,
  },
  text: {
    color: "rgb(95, 79, 61)",
    fontSize: 17,
  },
});
